namespace TightWiki.Contracts.DTOs
{
    /// <summary>
    /// Page data optimized for display - includes pre-rendered HTML from Engine.
    /// Used by Web.Bff after Engine processing.
    /// </summary>
    public class PageRenderedDto
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Title { get; set; } = string.Empty;
        public string Navigation { get; set; } = string.Empty;
        public string Namespace { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Pre-rendered HTML content from Engine transformation.
        /// </summary>
        public string RenderedBody { get; set; } = string.Empty;

        public int Revision { get; set; }
        public int MostCurrentRevision { get; set; }
        public bool IsHistoricalVersion => Revision != MostCurrentRevision;

        public DateTime ModifiedDate { get; set; }
        public string ModifiedByUserName { get; set; } = string.Empty;

        /// <summary>
        /// Table of contents generated by Engine.
        /// </summary>
        public List<TableOfContentsItemDto> TableOfContents { get; set; } = [];

        /// <summary>
        /// Outgoing wiki links found during rendering.
        /// </summary>
        public List<string> OutgoingLinks { get; set; } = [];

        /// <summary>
        /// Processing instructions from the page (e.g., HideFooterComments).
        /// </summary>
        public List<string> ProcessingInstructions { get; set; } = [];

        public List<string> Tags { get; set; } = [];
    }

    public class TableOfContentsItemDto
    {
        public int Level { get; set; }
        public string Text { get; set; } = string.Empty;
        public string Anchor { get; set; } = string.Empty;
    }
}
